//! Every syscall the rest of `zrt` is allowed to call.
//!
//! # The rules of this module
//!
//! * **One function per syscall.** Not per *concept*. There is a
//!   `dup2` because the supervisor redirects stdio and a `dup2_cloexec`
//!   because it hands fds to children; mixing them into a generic `dup` with a
//!   bool parameter is how an `FD_CLOEXEC` bug reaches production.
//! * **Every function returns `io::Result`.** The errno is the message. A
//!   `Result` is the only way an init can survive a failing syscall, and a
//!   `panic!` here would take down PID 1 and restart the whole supervisor.
//! * **Every `unsafe` block carries a `// SAFETY:` comment saying why the
//!   precondition holds.** The comment is the review surface. A binding
//!   generated by a macro cannot carry it, which is why this crate has exactly
//!   one dependency and hand-writes its FFI.
//! * **Interruptions are handled here, not by callers.** `EINTR` on
//!   `waitpid`, `accept`, `read` and `nanosleep` is normal in a process that
//!   receives signals as often as an init does. It is retried inside the
//!   wrapper so that no caller can forget.
//!
//! # What is deliberately absent
//!
//! Nothing that `std` already does correctly. `read`/`write` below are the
//! only overlap, and they exist because this crate is deliberately
//! fd-centric: descriptors are the vocabulary the reactor, the signal source
//! and the child tracker all speak, and `std::fs::File` is a second,
//! incompatible one. What `std` does *not* have is everything with
//! out-of-line arguments or platform-varying constants, and that is the bulk
//! of this file.

use core::ffi::CStr;
use std::ffi::{CString, OsStr};
use std::io;
use std::os::fd::RawFd;
use std::os::unix::ffi::OsStrExt;
use std::path::{Component, Path, PathBuf};

use crate::signals::Signal;

// ─────────────────────────────────────────────────────────────────────────────
// Process lifecycle
// ─────────────────────────────────────────────────────────────────────────────

/// `fork(2)`.
///
/// Returns `Ok(0)` in the child and `Ok(pid)` in the parent — the same
/// convention as libc, kept deliberately so nobody "fixes" it into an enum and
/// hides which side of the fork they are on.
///
/// # The child side
///
/// Everything after `fork` in a child is restricted to async-signal-safe
/// calls (`DESIGN.md` §9.1). This function is the raw syscall; the safe
/// wrapper with the pre-allocated argv and the single-exit child path is
/// [`crate::childproc::fork_tracked`]. Nothing here allocates.
pub fn fork() -> io::Result<i32> {
    // SAFETY: `fork` takes no arguments and has no preconditions. Its dangers
    // are all on the *child* side (only async-signal-safe calls, no locks held
    // by another thread, no allocator use), and those are obligations on the
    // caller, not on the call itself.
    let pid = unsafe { libc::fork() };
    if pid < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(pid)
    }
}

/// Leave the process without running any destructor, flushing any buffer or
/// running any exit hook.
///
/// The only legal exit for a forked child that could not `exec`. Running
/// `exit` (or unwinding) there would flush stdio buffers a *parent* also owns
/// — a classic double-flush that turns into duplicated log lines.
pub fn _exit(code: i32) -> ! {
    // SAFETY: `_exit` never returns, takes an int, and has no preconditions.
    // Its whole purpose is to be async-signal-safe.
    unsafe { libc::_exit(code) }
}

/// `execvp(3)`: search `PATH` and replace this process.
///
/// # Errors
///
/// On success this does not return — the process image is gone. So the error
/// type is [`core::convert::Infallible`]: a returned `Ok` is unrepresentable
/// and cannot be forgotten by a caller that pattern-matches.
///
/// The child path in a supervisor must be a *single* branch: if `execvp` fails,
/// [`execvp_or_exit`] turns it into `_exit(127)`, the universal "cannot execute"
/// status. There is no other way out of a forked child.
pub fn execvp(file: &CStr, argv: &[&CStr]) -> io::Result<core::convert::Infallible> {
    // The pointers handed to execvp must outlive the call, which they do:
    // `file` and every `argv` element borrow from live `CStr`s, and the
    // pointer array itself is built on the stack of this frame, which is alive
    // for the duration of the call.
    let ptrs: Vec<*const libc::c_char> = argv.iter().map(|a| a.as_ptr()).collect();
    let argv_ptr = if ptrs.is_empty() {
        std::ptr::null()
    } else {
        ptrs.as_ptr()
    };
    // SAFETY: `file` is a NUL-terminated C string by construction of `CStr`,
    // and `argv_ptr` points to a NUL-terminated array of pointers to
    // NUL-terminated strings (`argv` is required to end in a NUL, which the
    // caller must do — see `execvp_or_exit`). `execvp` reads them and does not
    // retain any of them past the call. On success it never returns.
    let _rc = unsafe { libc::execvp(file.as_ptr(), argv_ptr) };
    // Only reached on failure: -1 with errno set.
    Err(io::Error::last_os_error())
}

/// The only sanctioned child path: `execvp`, or die with 127.
///
/// Writing this as one function is the point. A child that fails to `exec`
/// must become an ordinary `Exited(127)` that the reconciler handles like any
/// other failed start — never a silent return into the parent's event loop,
/// which is the bug runit has been copied for having.
///
/// The caller must pass an `argv` whose **last element is a null pointer**
/// (`CStr` cannot hold one, so the terminator is passed separately as
/// `&[]`… see [`exec_argv`]).
pub fn execvp_or_exit(file: &CStr, argv: &[*const libc::c_char]) -> ! {
    if argv.last() == Some(&std::ptr::null()) {
        // SAFETY: the caller guarantees `argv` is a NUL-terminated array of
        // pointers to NUL-terminated strings (built by `exec_argv`), and the
        // array is alive on this frame's stack for the whole call.
        unsafe { libc::execvp(file.as_ptr(), argv.as_ptr()) };
    }
    _exit(127)
}

/// Build the `argv` array `execvp` wants from ordinary `CStr`s.
///
/// Preparing this **before** the fork is one of the three mitigations in
/// `DESIGN.md` §9.1: the child allocates nothing. It also appends the NUL
/// terminator that `CStr` itself cannot express.
pub fn exec_argv(args: &[&CStr]) -> Vec<*const libc::c_char> {
    let mut v: Vec<*const libc::c_char> = args.iter().map(|a| a.as_ptr()).collect();
    v.push(std::ptr::null());
    v
}

/// The current process id.
pub fn getpid() -> i32 {
    // SAFETY: `getpid` has no arguments, no preconditions, and never fails on
    // any POSIX system (it is the one syscall allowed to fail on ancient
    // kernels, and the fallback below keeps that from being a panic).
    let pid = unsafe { libc::getpid() };
    if pid < 0 {
        // Cannot happen; returning 0 is safer than panicking in an init.
        0
    } else {
        pid
    }
}

/// `setsid(2)`: become a session leader, detaching from the old terminal.
///
/// Mandatory before `TIOCSCTTY` for a console service: only a session leader
/// may acquire a controlling terminal, and without it a service that is
/// restarted would keep the dead console's tty.
pub fn setsid() -> io::Result<i32> {
    // SAFETY: no arguments, no preconditions. Fails with EPERM if the caller
    // is already a process-group leader, which is a real, reportable outcome.
    let rc = unsafe { libc::setsid() };
    if rc < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(rc)
    }
}

/// `kill(2)` on a single process.
pub fn kill_process(pid: i32, sig: Signal) -> io::Result<()> {
    // SAFETY: `kill` only inspects a pid and a signal number; there is no
    // pointer to get wrong. Passing pid 0 or -1 would signal a group, which is
    // why the group variant is a separate function: the two are too easy to
    // confuse at a call site.
    if unsafe { libc::kill(pid, sig.as_raw()) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `kill(2)` on a whole process group (negative pid).
///
/// This is how a service tree is stopped. It exists as its own function
/// because sending to `-pid` by accident is how an init kills itself.
pub fn kill_group(pid: i32, sig: Signal) -> io::Result<()> {
    // SAFETY: as above; a negative pid targets a process group.
    if unsafe { libc::kill(-pid, sig.as_raw()) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// File descriptors
// ─────────────────────────────────────────────────────────────────────────────

/// `close(2)`.
///
/// `EBADF` is a *bug indicator*, not a runtime condition, so it is reported
/// rather than swallowed — but it is also the single most likely benign
/// outcome when a child has already closed the fd, which is why
/// [`close_quietly`] exists.
pub fn close(fd: RawFd) -> io::Result<()> {
    // SAFETY: `close` takes an int; closing an invalid fd is an error return,
    // not undefined behaviour.
    if unsafe { libc::close(fd) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `close(2)` that maps `EBADF` to success.
///
/// Only for cleanup paths where the fd may legitimately be gone (a child that
/// died mid-setup, a double close in an error path).
pub fn close_quietly(fd: RawFd) -> io::Result<()> {
    match close(fd) {
        Err(e) if e.raw_os_error() == Some(libc::EBADF) => Ok(()),
        other => other,
    }
}

/// `dup2(2)`: make `newfd` refer to the same open file description as `oldfd`.
///
/// The one deliberate exception to the `FD_CLOEXEC` rule in this module: stdio
/// redirection happens *after* the CLOEXEC decision for the child, and the
/// target (0, 1, 2) must survive the exec.
pub fn dup2(oldfd: RawFd, newfd: RawFd) -> io::Result<RawFd> {
    // SAFETY: two ints. If `oldfd` is invalid the call fails with EBADF. If
    // `newfd` is already open, the kernel closes it atomically — there is no
    // window in which the supervisor has neither.
    if unsafe { libc::dup2(oldfd, newfd) } < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(newfd)
    }
}

/// `dup3(2)`: [`dup2`] that can also set `FD_CLOEXEC` atomically.
///
/// `dup2` has no "and set CLOEXEC" mode, and doing `dup2` then `fcntl` is a
/// race: a concurrent `fork` in the gap would inherit the fd without the flag.
/// An init forks constantly, so the race is not theoretical.
#[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd"
))]
pub fn dup3(oldfd: RawFd, newfd: RawFd, cloexec: bool) -> io::Result<RawFd> {
    let flags = if cloexec { libc::O_CLOEXEC } else { 0 };
    // SAFETY: three ints. `dup3` returns EINVAL rather than clobbering when
    // `oldfd == newfd`, so the "unconditional overwrite" contract of dup2 is
    // not silently violated.
    if unsafe { libc::dup3(oldfd, newfd, flags) } < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(newfd)
    }
}

/// `dup3(2)` for platforms that do not have it (OpenBSD < 5.9, older Apple).
///
/// Documented as a *degradation*: without `dup3` there is a theoretical window
/// between the `dup2` and the `fcntl`, so `cloexec: true` is only honoured for
/// fds that were not created by a concurrent `fork`. In a supervisor that
/// blocks signals and forks from a single thread, the window is not reachable.
#[cfg(not(any(
    target_os = "linux",
    target_os = "android",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd"
)))]
pub fn dup3(oldfd: RawFd, newfd: RawFd, cloexec: bool) -> io::Result<RawFd> {
    let fd = dup2(oldfd, newfd)?;
    if cloexec {
        set_cloexec(newfd, true)?;
    }
    Ok(fd)
}

/// `fcntl(F_SETFD, FD_CLOEXEC)` — mark a descriptor close-on-exec.
pub fn set_cloexec(fd: RawFd, on: bool) -> io::Result<()> {
    // SAFETY: `fcntl` is variadic; the argument for F_SETFD is an int, and
    // passing it as such through the varargs is what the ABI expects.
    let rc = unsafe { libc::fcntl(fd, libc::F_SETFD, if on { libc::FD_CLOEXEC } else { 0 }) };
    if rc == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// Read a descriptor's `FD_CLOEXEC` flag.
pub fn get_cloexec(fd: RawFd) -> io::Result<bool> {
    // SAFETY: as above, for F_GETFD which takes no argument.
    let rc = unsafe { libc::fcntl(fd, libc::F_GETFD) };
    if rc < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(rc & libc::FD_CLOEXEC != 0)
    }
}

/// `pipe2(2)`, always creating both ends with `O_CLOEXEC`.
///
/// Why always CLOEXEC: `DESIGN.md` §9 requires that a service inherits
/// exactly the fds it was given and nothing else. A supervisor that forgets
/// `FD_CLOEXEC` on one pipe leaks a writable pipe into every service it ever
/// starts, and a service that writes to it corrupts the supervisor's own
/// control channel. Making it the *only* behaviour of this function removes
/// the possibility of forgetting.
///
/// Use [`set_nonblocking`] on the read end afterwards if the pipe is going
/// into the reactor; the reactor is level-triggered and assumes non-blocking
/// descriptors.
#[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd",
    target_os = "dragonfly"
))]
pub fn pipe2(cloexec: bool) -> io::Result<(RawFd, RawFd)> {
    let flags = if cloexec { libc::O_CLOEXEC } else { 0 };
    let mut fds = [0 as RawFd; 2];
    // SAFETY: `fds` is a live, correctly aligned array of exactly two ints,
    // which is what pipe2 writes. On failure it is untouched.
    if unsafe { libc::pipe2(fds.as_mut_ptr(), flags) } == 0 {
        Ok((fds[0], fds[1]))
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `pipe(2)` plus an explicit `FD_CLOEXEC` loop, for platforms without
/// `pipe2`.
///
/// Degradation: the flag is set after the pipe exists, so a concurrent `fork`
/// in that window inherits both ends. Single-threaded supervisors — the only
/// kind this project builds — cannot hit it.
#[cfg(not(any(
    target_os = "linux",
    target_os = "android",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd",
    target_os = "dragonfly"
)))]
pub fn pipe2(cloexec: bool) -> io::Result<(RawFd, RawFd)> {
    let mut fds = [0 as RawFd; 2];
    // SAFETY: `fds` is a live array of two ints, exactly what pipe writes.
    if unsafe { libc::pipe(fds.as_mut_ptr()) } != 0 {
        return Err(io::Error::last_os_error());
    }
    if cloexec {
        for fd in fds {
            if let Err(e) = set_cloexec(fd, true) {
                let _ = close(fds[0]);
                let _ = close(fds[1]);
                return Err(e);
            }
        }
    }
    Ok((fds[0], fds[1]))
}

/// `O_NONBLOCK` on a descriptor.
///
/// Every fd handed to the reactor must be non-blocking: the reactor reports
/// *level* readiness (see [`crate::reactor`]), and a blocking descriptor in a
/// level-triggered loop is a deadlock.
pub fn set_nonblocking(fd: RawFd, on: bool) -> io::Result<()> {
    // Read the current flags and write them back with only `O_NONBLOCK`
    // changed.
    //
    // `F_SETFL` *replaces* the whole word, so passing a bare
    // `O_NONBLOCK` silently clears every other descriptor flag — including
    // `O_CLOEXEC`, which is the one that matters most. A descriptor marked
    // non-blocking and then made inheritable leaks into every `exec` the
    // process ever does, which is exactly the bug the exec-error pipe depends
    // on closing.
    //
    // SAFETY: `F_GETFL` returns the flag word in the int `out` points at; it
    // takes no descriptor state by reference. The pointer is a live local.
    let mut current: libc::c_int = 0;
    if unsafe { libc::fcntl(fd, libc::F_GETFL, &raw mut current) } == -1 {
        return Err(io::Error::last_os_error());
    }
    let updated = if on {
        current | libc::O_NONBLOCK
    } else {
        current & !libc::O_NONBLOCK
    };
    // SAFETY: `F_SETFL` takes the flag word as an int argument, passed as
    // such. `current` was populated by the `F_GETFL` above.
    if unsafe { libc::fcntl(fd, libc::F_SETFL, updated) } == -1 {
        return Err(io::Error::last_os_error());
    }
    Ok(())
}

/// `socketpair(2)`, both ends `O_CLOEXEC` and `SOCK_NONBLOCK`.
///
/// Used by tests and by the readiness handshake: a socket pair gives a
/// connection with a clean half-close (`shutdown`), which a pipe cannot.
pub fn socketpair() -> io::Result<(RawFd, RawFd)> {
    let mut fds = [0 as RawFd; 2];
    let flags = libc::SOCK_STREAM | socket_flags();
    // SAFETY: `fds` is a live array of two ints; `socketpair` writes exactly
    // two. The domain is AF_UNIX, which every platform in scope supports.
    if unsafe { libc::socketpair(libc::AF_UNIX, flags, 0, fds.as_mut_ptr()) } != 0 {
        return Err(io::Error::last_os_error());
    }
    for fd in fds {
        if let Err(e) = finish_socket_fd(fd) {
            let _ = close_quietly(fds[0]);
            let _ = close_quietly(fds[1]);
            return Err(e);
        }
    }
    Ok((fds[0], fds[1]))
}

/// The type bits to pass to `socket`/`socketpair`, so the descriptor comes out
/// close-on-exec and non-blocking.
///
/// Linux and the BSDs accept `SOCK_CLOEXEC | SOCK_NONBLOCK` as creation
/// flags, atomically. Darwin defines neither, so there the call is made plain
/// and finished afterwards with [`finish_socket_fd`]. Both spellings end in
/// the same place, so no caller has to know which one it is on.
#[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd",
    target_os = "dragonfly"
))]
const fn socket_flags() -> libc::c_int {
    libc::SOCK_CLOEXEC | libc::SOCK_NONBLOCK
}

/// Darwin has neither creation flag, so the call is made plain.
#[cfg(target_vendor = "apple")]
const fn socket_flags() -> libc::c_int {
    0
}

/// `recvmsg(2)` flags, with `MSG_CMSG_CLOEXEC` where the platform has it.
///
/// Linux, the BSDs and DragonFly define it, and there the received descriptor
/// is close-on-exec *at the kernel level*. Darwin does not have it, and there
/// the flag is set with an `fcntl` immediately after — the same documented
/// race as [`accept4_nocloexec`], for the same reason.
#[cfg(not(target_vendor = "apple"))]
const fn recv_flags() -> libc::c_int {
    libc::MSG_CMSG_CLOEXEC
}

/// Darwin has no `MSG_CMSG_CLOEXEC`.
#[cfg(target_vendor = "apple")]
const fn recv_flags() -> libc::c_int {
    0
}

/// Apply close-on-exec and non-blocking to a socket that was created without
/// the atomic creation flags.
///
/// Runs unconditionally, so the Darwin path and the rest of the crate are the
/// same code. The cost is two `fcntl`s on a non-Darwin machine, on sockets
/// that are created a handful of times per boot.
fn finish_socket_fd(fd: RawFd) -> io::Result<()> {
    set_cloexec(fd, true)?;
    set_nonblocking(fd, true)?;
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// Waiting for children
// ─────────────────────────────────────────────────────────────────────────────

/// How a child terminated.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ExitStatus {
    /// `exit(n)` / return from `main`. `n` is the low 8 bits of the status.
    Exited(i32),
    /// Killed by a signal, with or without a core dump.
    Signaled {
        /// The signal number that killed it, e.g. 9 for `SIGKILL`.
        signal: i32,
        /// Whether the kernel also wrote a core file.
        core_dumped: bool,
    },
    /// Stopped or continued, reported by a `WUNTRACED` `waitpid`.
    ///
    /// zinit never uses `WUNTRACED`; a supervisor that traced its children
    /// would stop supervising them. The variant exists so that a surprising
    /// status word is representable instead of being silently mis-decoded.
    Reported(i32),
}

impl ExitStatus {
    /// True only for `exit(0)`. A signal death is never "success", even
    /// `SIGTERM` — the service did not choose to stop.
    pub fn is_success(self) -> bool {
        matches!(self, ExitStatus::Exited(0))
    }

    /// The number to report to the operator and to `zcore`.
    ///
    /// A signalled child reports `128 + signal`, the shell convention, because
    /// every log format, every monitoring system and every human already knows
    /// it. `Exited(0)` reports 0.
    pub fn code(self) -> i32 {
        match self {
            ExitStatus::Exited(c) => c,
            ExitStatus::Signaled { signal, .. } => 128 + signal,
            ExitStatus::Reported(c) => c,
        }
    }
}

/// One completed `waitpid`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Waited {
    /// The child that changed state. Useful with `waitpid(-1, ...)`.
    pub pid: i32,
    /// How it terminated.
    pub status: ExitStatus,
}

/// Decode a raw `wait(2)` status word.
///
/// Split out because the encoding is a bit-packed kernel ABI and getting the
/// order of the tests wrong is the classic bug (`WIFSIGNALED` before
/// `WIFEXITED` inverts the meaning of everything).
pub fn decode_status(raw: i32) -> ExitStatus {
    // These are `const fn`s in libc, pure bit operations on the status word.
    // The order of the tests is the whole point: checking `WIFSIGNALED` before
    // `WIFEXITED` inverts the meaning of every status, which is the single
    // most common bug in hand-rolled `wait(2)` decoders.
    if libc::WIFEXITED(raw) {
        ExitStatus::Exited(libc::WEXITSTATUS(raw))
    } else if libc::WIFSIGNALED(raw) {
        ExitStatus::Signaled {
            signal: libc::WTERMSIG(raw),
            core_dumped: libc::WCOREDUMP(raw),
        }
    } else {
        ExitStatus::Reported(raw)
    }
}

/// `waitpid(pid, WNOHANG)` for one child, or for any child if `pid` is `-1`.
///
/// `Ok(None)` is the normal, expected answer: "nothing has changed yet". The
/// distinction matters because an init calls this in a loop and must be able to
/// tell "no child died" from "the kernel is broken".
pub fn waitpid_nohang(pid: i32) -> io::Result<Option<Waited>> {
    loop {
        let mut status: libc::c_int = 0;
        // SAFETY: `&raw mut status` is a live, aligned `c_int`; `waitpid`
        // writes exactly one there. `pid == -1` and `0` have their documented
        // POSIX meanings ("any child", "any child in my group").
        let rc = unsafe { libc::waitpid(pid, &raw mut status, libc::WNOHANG) };
        if rc > 0 {
            return Ok(Some(Waited {
                pid: rc,
                status: decode_status(status),
            }));
        }
        if rc == 0 {
            return Ok(None);
        }
        let err = io::Error::last_os_error();
        // `ECHILD` means there is no such child: it exited and was already
        // reaped, or it was never ours. Not an error for a reaper.
        if err.raw_os_error() == Some(libc::ECHILD) {
            return Ok(None);
        }
        if err.kind() != io::ErrorKind::Interrupted {
            return Err(err);
        }
        // EINTR: a signal arrived between the check and the call. Retry.
    }
}

/// `waitpid(pid, 0)` — block until the child changes state.
///
/// Retries `EINTR` internally, which is the entire reason this function
/// exists: a supervisor has `SIGCHLD` blocked and reaps from the event loop, so
/// a raw `waitpid` interrupted by an unrelated signal would otherwise surface
/// as a spurious error.
pub fn waitpid_blocking(pid: i32) -> io::Result<Waited> {
    loop {
        let mut status: libc::c_int = 0;
        // SAFETY: as `waitpid_nohang`, but without WNOHANG.
        let rc = unsafe { libc::waitpid(pid, &raw mut status, 0) };
        if rc > 0 {
            return Ok(Waited {
                pid: rc,
                status: decode_status(status),
            });
        }
        let err = io::Error::last_os_error();
        if err.kind() != io::ErrorKind::Interrupted {
            return Err(err);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Byte-level I/O
// ─────────────────────────────────────────────────────────────────────────────

/// `read(2)` on a raw descriptor, retrying `EINTR`.
///
/// This crate is fd-centric by design — descriptors are what the reactor, the
/// signal source and the child tracker all speak — so `std::io::Read` on a
/// `File` is a second, incompatible vocabulary. This is the small bridge: same
/// errno, same `EINTR` policy, no allocation and no `BufReader` state that a
/// forked child would duplicate.
///
/// `Ok(0)` means end of file, which is *data*, not an error. In a supervisor
/// that distinction is load-bearing: a closed notify pipe is how a service
/// says "I am done", and it arrives as a zero-length read.
pub fn read(fd: RawFd, buf: &mut [u8]) -> io::Result<usize> {
    if buf.is_empty() {
        return Ok(0);
    }
    loop {
        // SAFETY: `buf` is a live, uniquely borrowed slice and `read` is told
        // its exact length; the kernel writes at most that many bytes and
        // retains no pointer.
        let n = unsafe { libc::read(fd, buf.as_mut_ptr().cast::<libc::c_void>(), buf.len()) };
        if n >= 0 {
            return Ok(n as usize);
        }
        let err = io::Error::last_os_error();
        if err.kind() != io::ErrorKind::Interrupted {
            return Err(err);
        }
    }
}

/// `write(2)` on a raw descriptor, retrying `EINTR`.
///
/// A short write is reported as-is rather than looped. Looping would hide a
/// partially written log line or a partially sent control frame, and both of
/// those are decisions the *caller* has to make: this layer does not know
/// whether a half-written frame is retryable.
pub fn write(fd: RawFd, buf: &[u8]) -> io::Result<usize> {
    if buf.is_empty() {
        return Ok(0);
    }
    loop {
        // SAFETY: `buf` is a live, immutable slice and `write` is told its
        // exact length; the kernel only reads it.
        let n = unsafe { libc::write(fd, buf.as_ptr().cast::<libc::c_void>(), buf.len()) };
        if n >= 0 {
            return Ok(n as usize);
        }
        let err = io::Error::last_os_error();
        if err.kind() != io::ErrorKind::Interrupted {
            return Err(err);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Clocks
// ─────────────────────────────────────────────────────────────────────────────

/// Which clock a [`try_clock_gettime_ms`] call reads.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ClockId {
    /// `CLOCK_MONOTONIC`: boot-relative, never jumps. Deadlines only.
    Monotonic,
    /// `CLOCK_REALTIME`: wall clock. Human-facing output only.
    Realtime,
}

impl ClockId {
    /// The `clockid_t` this variant maps to.
    const fn raw(self) -> libc::clockid_t {
        match self {
            // `CLOCK_MONOTONIC` has existed on every POSIX platform zinit
            // targets; the runtime probe in `clock::clock_source` is about
            // kernels and containers that lie about it, not about the header.
            ClockId::Monotonic => libc::CLOCK_MONOTONIC,
            ClockId::Realtime => libc::CLOCK_REALTIME,
        }
    }
}

/// `clock_gettime(CLOCK_MONOTONIC|CLOCK_REALTIME)` in milliseconds.
///
/// Nanoseconds are truncated, not rounded: a deadline that fires a hair early
/// is harmless, one that fires a hair late is a bug report. Overflow of the
/// 64-bit millisecond counter is decades away and saturates rather than wraps.
pub fn clock_gettime_ms(id: ClockId) -> u64 {
    match try_clock_gettime_ms(id) {
        Ok(ms) => ms,
        Err(e) => {
            // A failing clock is catastrophic but not a reason to abort PID 1.
            // Returning 0 keeps the supervisor running with a visibly broken
            // clock; the probe that produced this path already logged why.
            crate::report::announce_degradation(&format!("clock_gettime failed: {e}"));
            0
        }
    }
}

/// [`clock_gettime_ms`] with the error preserved, for probes and tests.
pub fn try_clock_gettime_ms(id: ClockId) -> io::Result<u64> {
    let mut ts = libc::timespec {
        tv_sec: 0,
        tv_nsec: 0,
    };
    // SAFETY: `ts` is a live, aligned `timespec` on this frame and
    // `clock_gettime` writes exactly one. It does not retain the pointer.
    if unsafe { libc::clock_gettime(id.raw(), &raw mut ts) } != 0 {
        return Err(io::Error::last_os_error());
    }
    if ts.tv_sec < 0 || ts.tv_nsec < 0 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "clock_gettime returned a negative time",
        ));
    }
    let ms = (ts.tv_sec as u64)
        .saturating_mul(1000)
        .saturating_add(ts.tv_nsec as u64 / 1_000_000);
    Ok(ms)
}

// ─────────────────────────────────────────────────────────────────────────────
// Files and paths
// ─────────────────────────────────────────────────────────────────────────────

/// `open(2)` with `O_CLOEXEC` always set.
///
/// There is no way to get a non-CLOEXEC fd from this module on purpose. The
/// only descriptors that must survive an exec are the ones stdio and the
/// control protocol hold, and those are duplicated with [`dup2`]/[`dup3`]
/// explicitly.
pub fn open_cloexec(path: &Path, flags: i32, mode: u32) -> io::Result<RawFd> {
    openat_nofollow(libc::AT_FDCWD, path, flags, mode)
}

/// `openat(2)` with `O_NOFOLLOW` and `O_CLOEXEC` always set.
///
/// `O_NOFOLLOW` because the supervisor's whole security argument rests on not
/// being tricked by a symlink at a path it is about to chown, chmod or mount
/// (`DESIGN.md` §9 rule 4). `O_CLOEXEC` for the leak reason in [`pipe2`].
///
/// Pass `AT_FDCWD` as `dirfd` for an absolute path; this exists so a caller
/// can open relative to a directory fd it already holds, which closes the
/// TOCTOU window that `open(path)` + `fchown(path)` leaves open.
pub fn openat_nofollow(dirfd: RawFd, path: &Path, flags: i32, mode: u32) -> io::Result<RawFd> {
    let c = cpath(path)?;
    let flags = flags | libc::O_NOFOLLOW | libc::O_CLOEXEC;
    // SAFETY: `c` is a NUL-terminated string alive for this call, `dirfd` is
    // either AT_FDCWD or a real descriptor the caller owns, and `mode` is only
    // consulted when O_CREAT is set. The kernel copies the path; it does not
    // retain the pointer.
    let fd = unsafe { libc::openat(dirfd, c.as_ptr(), flags, mode as libc::c_uint) };
    if fd < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(fd)
    }
}

/// `fchown(2)` on an **open descriptor**.
///
/// Only ever on an fd, never on a path: chowning by name is a TOCTOU race
/// where the file can be swapped for a symlink between the check and the
/// call. That is rule 4 in `DESIGN.md` §9 and it is not negotiable.
pub fn fchown(fd: RawFd, uid: u32, gid: u32) -> io::Result<()> {
    // SAFETY: three ints, no pointers. The descriptor must be open; a stale
    // one returns EBADF, which is exactly the signal we want.
    if unsafe { libc::fchown(fd, uid, gid) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `fchmod(2)` on an open descriptor. Same TOCTOU argument as [`fchown`].
pub fn fchmod(fd: RawFd, mode: u32) -> io::Result<()> {
    // SAFETY: two ints, no pointers.
    if unsafe { libc::fchmod(fd, mode as libc::mode_t) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `mkdir(2)` for a single component, without following a trailing symlink.
pub fn mkdir(path: &Path, mode: u32) -> io::Result<()> {
    let c = cpath(path)?;
    // SAFETY: `c` is NUL-terminated and alive for the call; `mode` is only
    // used by this very syscall.
    if unsafe { libc::mkdir(c.as_ptr(), mode as libc::mode_t) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `mkdir -p`: create every missing component, succeed if it already exists.
///
/// An existing component that is **not** a directory is `ENOTDIR` — a real
/// error, never ignored. Silently continuing there is how an init ends up
/// writing its socket into a file.
pub fn mkdir_p(path: &Path, mode: u32) -> io::Result<()> {
    let mut cur = PathBuf::new();
    for comp in path.components() {
        match comp {
            Component::RootDir => cur.push("/"),
            Component::CurDir => {}
            Component::ParentDir => {
                cur.pop();
            }
            Component::Prefix(_) | Component::Normal(_) => cur.push(comp.as_os_str()),
        }
        if cur.as_os_str().is_empty() {
            continue;
        }
        match mkdir(&cur, mode) {
            Ok(()) => {}
            Err(e) if e.raw_os_error() == Some(libc::EEXIST) => {
                // Already there. It must be a directory, or we are about to
                // create things *inside* a regular file.
                match stat_is_dir(&cur)? {
                    true => {}
                    false => {
                        return Err(io::Error::new(
                            io::ErrorKind::AlreadyExists,
                            format!("{} exists and is not a directory", cur.display()),
                        ));
                    }
                }
            }
            Err(e) if e.raw_os_error() == Some(libc::ENOENT) => {
                // A concurrent `mkdir -p` beat us to it, or a parent really is
                // missing because it is a dangling symlink. Either way the
                // recursive call from the next component is the fix, and if
                // there is no next component this is the genuine error.
                return Err(e);
            }
            Err(e) => return Err(e),
        }
    }
    Ok(())
}

/// Whether `path` exists and is a directory.
pub fn stat_is_dir(path: &Path) -> io::Result<bool> {
    let c = cpath(path)?;
    let mut st: libc::stat = unsafe { core::mem::zeroed() };
    // SAFETY: `st` is a live, aligned `stat` of the size libc's `stat` type
    // describes, and `lstat` writes exactly one. `c` is NUL-terminated.
    if unsafe { libc::lstat(c.as_ptr(), &raw mut st) } != 0 {
        return Err(io::Error::last_os_error());
    }
    Ok(st.st_mode & libc::S_IFMT == libc::S_IFDIR)
}

/// `(device, inode)` of an existing path.
///
/// Used to detect that a pidfile or a socket belongs to *this* boot and
/// *this* filesystem — a stale `/run` file from the previous run must not be
/// mistaken for a live one. Reports the target of a symlink, deliberately:
/// the question is "what does this path resolve to", and a dangling symlink
/// is an error here, not a special case.
pub fn stat_dev_ino(path: &Path) -> io::Result<(u64, u64)> {
    let c = cpath(path)?;
    let mut st: libc::stat = unsafe { core::mem::zeroed() };
    // SAFETY: as `stat_is_dir`, with `stat` instead of `lstat`.
    if unsafe { libc::stat(c.as_ptr(), &raw mut st) } != 0 {
        return Err(io::Error::last_os_error());
    }
    Ok((st.st_dev as u64, st.st_ino as u64))
}

/// `readlink(2)` into an owned `PathBuf`.
///
/// A symlink whose target is longer than 255 bytes comes back as
/// `ENAMETOOLONG` from a fixed buffer, which is reported rather than
/// silently truncated. Init symlinks (`/run` → `/var/run`) are short; if one
/// ever is not, the operator should know rather than debug a truncated path.
pub fn readlink(path: &Path) -> io::Result<PathBuf> {
    let c = cpath(path)?;
    let mut buf = vec![0u8; 4096];
    // SAFETY: `buf` is a live allocation of exactly `buf.len()` bytes, which
    // is the size passed in `n`. `readlink` writes at most `n` bytes and does
    // not NUL-terminate, so the length is taken from the return value.
    let n = unsafe {
        libc::readlink(
            c.as_ptr(),
            buf.as_mut_ptr().cast::<libc::c_char>(),
            buf.len(),
        )
    };
    if n < 0 {
        return Err(io::Error::last_os_error());
    }
    let read = n as usize;
    if read == buf.len() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "symlink target longer than the 4096-byte readlink buffer",
        ));
    }
    buf.truncate(read);
    Ok(PathBuf::from(OsStr::from_bytes(&buf)))
}

/// `unlink(2)`.
pub fn unlink(path: &Path) -> io::Result<()> {
    let c = cpath(path)?;
    // SAFETY: NUL-terminated path, no other preconditions.
    if unsafe { libc::unlink(c.as_ptr()) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `rename(2)`: atomic replace.
///
/// This is how a service's state file is published, and why it is `rename` and
/// not "write, then rename the temp": a reader either sees the whole old file
/// or the whole new one.
pub fn rename(from: &Path, to: &Path) -> io::Result<()> {
    let a = cpath(from)?;
    let b = cpath(to)?;
    // SAFETY: two NUL-terminated paths, both alive for the call.
    if unsafe { libc::rename(a.as_ptr(), b.as_ptr()) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Sockets
// ─────────────────────────────────────────────────────────────────────────────

/// `SOCK_STREAM | SOCK_CLOEXEC` on `AF_UNIX`.
pub fn socket_unix_stream() -> io::Result<RawFd> {
    socket_unix(libc::SOCK_STREAM)
}

/// `SOCK_DGRAM | SOCK_CLOEXEC` on `AF_UNIX`.
pub fn socket_unix_dgram() -> io::Result<RawFd> {
    socket_unix(libc::SOCK_DGRAM)
}

fn socket_unix(kind: libc::c_int) -> io::Result<RawFd> {
    // SAFETY: `socket` takes three ints; AF_UNIX with SOCK_STREAM or
    // SOCK_DGRAM and protocol 0 is the canonical portable form.
    let fd = unsafe { libc::socket(libc::AF_UNIX, kind | socket_flags(), 0) };
    if fd < 0 {
        return Err(io::Error::last_os_error());
    }
    match finish_socket_fd(fd) {
        Ok(()) => Ok(fd),
        Err(e) => {
            // The descriptor exists and would otherwise leak for the rest of
            // the process — in a supervisor, the difference between a failed
            // call and a mystery fd three services later.
            let _ = close_quietly(fd);
            Err(e)
        }
    }
}

/// `bind(2)` for a `AF_UNIX` socket.
///
/// A path starting with `@` binds in the Linux **abstract** namespace (byte 0
/// of `sun_path`, no filesystem entry, no cleanup, survives a full `/run`
/// remount). Every other path is a real filesystem path, which is what the BSD
/// builds use and what the config format can therefore rely on.
///
/// `sun_path` is 108 bytes on Linux and 104 on the BSDs; a longer path is
/// rejected locally with `InvalidInput` rather than truncated, because a
/// truncated socket path is a socket nobody else can find.
pub fn bind_unix(fd: RawFd, path: &Path) -> io::Result<()> {
    let bytes = path.as_os_str().as_bytes();
    let (abstract_ns, tail) = match bytes.split_first() {
        Some((b'@', rest)) => (true, rest),
        _ => (false, bytes),
    };
    if tail.contains(&0) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "unix socket path contains an interior NUL",
        ));
    }
    let mut addr: libc::sockaddr_un = unsafe { core::mem::zeroed() };
    addr.sun_family = libc::AF_UNIX as libc::sa_family_t;
    let cap = addr.sun_path.len();
    if tail.len() >= cap {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!(
                "unix socket path is {} bytes; sun_path holds {}",
                tail.len(),
                cap - 1
            ),
        ));
    }
    if abstract_ns {
        // Leave sun_path[0] as NUL; that is precisely what makes it abstract.
        for (i, b) in tail.iter().enumerate() {
            addr.sun_path[i + 1] = *b as libc::c_char;
        }
    } else {
        for (i, b) in tail.iter().enumerate() {
            addr.sun_path[i] = *b as libc::c_char;
        }
        // NUL terminate: `addr` is zeroed, and the check above guarantees
        // there is room for the terminator.
    }
    // SAFETY: `addr` is a live, correctly aligned `sockaddr_un` with
    // sun_family set and a NUL-terminated (or abstract) path; the length
    // passed is the real length, not `size_of`, because the kernel reads
    // `sun_path` up to the first NUL and the abstract form has none.
    // Both spellings of the length happen to be `tail.len() + 1`, and that is
    // not a coincidence: the abstract form's leading NUL *is* the first byte
    // of the path. They are written as one expression because a reader who
    // thinks the two lengths differ will start "fixing" this.
    let len = std::mem::size_of::<libc::sa_family_t>() + tail.len() + 1;
    if unsafe {
        libc::bind(
            fd,
            (&raw const addr).cast::<libc::sockaddr>(),
            len as libc::socklen_t,
        )
    } != 0
    {
        return Err(io::Error::last_os_error());
    }
    Ok(())
}

/// `listen(2)`.
pub fn listen(fd: RawFd, backlog: i32) -> io::Result<()> {
    // SAFETY: an int and an int. A negative backlog is rejected by the kernel.
    if unsafe { libc::listen(fd, backlog) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `accept4(2)` with `SOCK_CLOEXEC`, retrying `EINTR`.
///
/// `EAGAIN` is returned to the caller unchanged: on a non-blocking listening
/// socket it is the normal "nothing yet" answer, and the event loop is
/// structured to treat it as such.
#[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "freebsd",
    target_os = "netbsd",
    target_os = "openbsd",
    target_os = "dragonfly"
))]
pub fn accept4_nocloexec(fd: RawFd) -> io::Result<RawFd> {
    loop {
        // SAFETY: `accept4` writes the new descriptor through its return
        // value only; no out-pointers, so there is nothing to get wrong here.
        let conn = unsafe {
            libc::accept4(
                fd,
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                libc::SOCK_CLOEXEC,
            )
        };
        if conn >= 0 {
            return Ok(conn);
        }
        let err = io::Error::last_os_error();
        if err.kind() != io::ErrorKind::Interrupted {
            return Err(err);
        }
    }
}

/// `accept4_nocloexec` where `accept4(2)` does not exist.
///
/// Darwin is the case in scope. The flag is applied with `fcntl` immediately
/// afterwards, which is a race in a program that forks concurrently — the
/// whole reason `accept4` exists. zinit's supervisor is single-threaded and
/// forks only from its event loop, so the window is not reachable; it is
/// documented rather than pretended away.
#[cfg(target_vendor = "apple")]
pub fn accept4_nocloexec(fd: RawFd) -> io::Result<RawFd> {
    loop {
        // SAFETY: null out-pointers are explicitly allowed by `accept(2)`, and
        // the return value is the only thing written.
        let conn = unsafe { libc::accept(fd, std::ptr::null_mut(), std::ptr::null_mut()) };
        if conn >= 0 {
            return match set_cloexec(conn, true) {
                Ok(()) => Ok(conn),
                Err(e) => {
                    let _ = close_quietly(conn);
                    Err(e)
                }
            };
        }
        let err = io::Error::last_os_error();
        if err.kind() != io::ErrorKind::Interrupted {
            return Err(err);
        }
    }
}

/// Send one byte of payload plus one file descriptor over a unix socket
/// (`SCM_RIGHTS`).
///
/// This is how the supervisor hands a service its log fd or its notify fd
/// *without* letting it inherit anything else: one syscall, one fd, and the
/// receiving side gets exactly what was sent. The alternative — arranging fd
/// numbers in advance so the child inherits them — is the thing `FD_CLOEXEC`
/// exists to prevent.
///
/// Returns the number of payload bytes written, which is 0 or 1; a large
/// payload is truncated, and that is the caller's business.
pub fn send_fd(sock: RawFd, payload: &[u8], fd: RawFd) -> io::Result<usize> {
    let mut byte = [payload.first().copied().unwrap_or(0u8)];
    let mut iov = libc::iovec {
        iov_base: byte.as_mut_ptr().cast::<libc::c_void>(),
        iov_len: byte.len(),
    };
    // One control message carrying exactly one fd. The layout is computed by
    // hand rather than with the CMSG_* macros because those differ across
    // platforms in both availability and signature, and this file is the one
    // place where a mistake is a memory-safety bug.
    //
    // `CMSG_LEN`-equivalent: header + the data word, both rounded up to the
    // control buffer's alignment. `cmsg_len` and `msg_controllen` are `size_t`
    // on Linux and `u32` (`socklen_t`) on the BSDs, which is why every
    // assignment here goes through `as _` — the target type is inferred from
    // the field and no cast can be wrong for the platform it is compiled on.
    let hdr_size = hdr_size_of::<libc::cmsghdr>();
    let data_len = cmsg_align(len_of::<RawFd>());
    let space = hdr_size + data_len;
    let mut cmsg_buf = [0u8; 64];
    if space > cmsg_buf.len() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "SCM_RIGHTS control buffer too small",
        ));
    }
    {
        // SAFETY: `cmsg_buf` is a live `[u8; 64]` with alignment 1; the
        // `cmsghdr` written into it is 8-aligned by construction (64 is a
        // multiple of 8), which is what the kernel requires of a control
        // message. The write stays within `hdr_size`.
        let hdr = cmsg_buf.as_mut_ptr().cast::<libc::cmsghdr>();
        unsafe {
            core::ptr::write_bytes(hdr, 0, 1);
            (*hdr).cmsg_len = (hdr_size + cmsg_align(size_of::<libc::c_int>())) as _;
            (*hdr).cmsg_level = libc::SOL_SOCKET;
            (*hdr).cmsg_type = libc::SCM_RIGHTS;
        }
        // SAFETY: the data word starts at `hdr_size`, is 4-byte aligned, and
        // `space` covers hdr_size + align(sizeof(c_int)) = 8 + 4 + 4 = 16.
        let data = unsafe { cmsg_buf.as_mut_ptr().add(hdr_size).cast::<libc::c_int>() };
        unsafe { core::ptr::write(data, fd) };
    }
    let mut msg: libc::msghdr = unsafe { core::mem::zeroed() };
    msg.msg_iov = &raw mut iov;
    msg.msg_iovlen = 1;
    msg.msg_control = cmsg_buf.as_mut_ptr().cast::<libc::c_void>();
    msg.msg_controllen = (hdr_size + data_len) as _;
    let _ = space;
    // SAFETY: `iov`/`msg` are live and correctly aligned; `msg_iovlen` matches
    // the one-element array; `msg_control` points at a buffer of exactly
    // `msg_controllen` bytes holding one well-formed SCM_RIGHTS message.
    let sent = unsafe { libc::sendmsg(sock, &raw const msg, libc::MSG_NOSIGNAL) };
    if sent < 0 {
        return Err(io::Error::last_os_error());
    }
    Ok(sent as usize)
}

/// Receive up to one payload byte plus at most one file descriptor.
pub fn recv_fd(sock: RawFd) -> io::Result<(u8, Option<RawFd>)> {
    let mut byte = [0u8; 1];
    let mut iov = libc::iovec {
        iov_base: byte.as_mut_ptr().cast::<libc::c_void>(),
        iov_len: 1,
    };
    let mut cmsg_buf = [0u8; 64];
    let mut msg: libc::msghdr = unsafe { core::mem::zeroed() };
    msg.msg_iov = &raw mut iov;
    msg.msg_iovlen = 1;
    msg.msg_control = cmsg_buf.as_mut_ptr().cast::<libc::c_void>();
    msg.msg_controllen = cmsg_buf.len() as _;
    // SAFETY: both buffers are live with their exact lengths recorded in
    // `msg`; `recvmsg` will not write past `msg_controllen` in `msg_control`
    // or `msg_iovlen` in the iovec. Where `MSG_CMSG_CLOEXEC` exists the
    // received descriptor is close-on-exec *at the kernel level*.
    let got = unsafe { libc::recvmsg(sock, &raw mut msg, recv_flags()) };
    if got < 0 {
        return Err(io::Error::last_os_error());
    }
    let mut out_fd: Option<RawFd> = None;
    if msg.msg_controllen as usize >= hdr_size_of::<libc::cmsghdr>() {
        // SAFETY: the kernel wrote a control message into `cmsg_buf` and
        // reported its length in `msg_controllen`, which is checked above.
        // Iterating with CMSG_FIRSTHDR/CMSG_NXTHDR is the only legal way to
        // walk it; both are pure pointer arithmetic over the kernel-written
        // buffer.
        unsafe {
            let mut cmsg = libc::CMSG_FIRSTHDR(&raw const msg);
            while !cmsg.is_null() {
                if (*cmsg).cmsg_level == libc::SOL_SOCKET && (*cmsg).cmsg_type == libc::SCM_RIGHTS {
                    let data = libc::CMSG_DATA(cmsg);
                    out_fd = Some(core::ptr::read(data.cast::<libc::c_int>()));
                    break;
                }
                cmsg = libc::CMSG_NXTHDR(&raw const msg, cmsg);
            }
        }
    }
    let out_fd = match out_fd {
        Some(f) => match set_cloexec(f, true) {
            // On Linux and the BSDs `MSG_CMSG_CLOEXEC` already did this and
            // the `fcntl` merely confirms it; on Darwin it is the only thing
            // making it true.
            Ok(()) => Some(f),
            Err(e) => {
                let _ = close_quietly(f);
                return Err(e);
            }
        },
        None => None,
    };
    Ok((byte[0], out_fd))
}

// ─────────────────────────────────────────────────────────────────────────────
// Mount, hostname, terminal
// ─────────────────────────────────────────────────────────────────────────────

/// `mount(2)`, with the differences between platforms resolved here.
///
/// This is the ugliest signature in the crate, and that is the point of
/// having it: `mount(2)` takes five arguments on Linux (with a *filesystem
/// type*) and four on the BSDs (which infer the type from the mount helper
/// being used), and NetBSD adds a sixth. Rather than pushing a `#[cfg]` onto
/// every caller — there will be exactly one, in the tmpfs stage — the shape
/// difference is absorbed here and the *semantic* difference is documented:
///
/// * Linux needs `fstype` ("tmpfs"); the BSDs ignore it and take the type
///   from the `data` string instead. Passing `None` on a BSD is legal.
/// * The BSD flag values are `c_int`, Linux's are `c_ulong`, so they are
///   taken as `u32` and cast.
pub fn mount(
    source: Option<&Path>,
    target: &Path,
    fstype: Option<&str>,
    flags: u32,
    data: Option<&str>,
) -> io::Result<()> {
    let src = match source {
        Some(p) => Some(cpath(p)?),
        None => None,
    };
    let typ = match fstype {
        Some(s) => Some(cstr(s)?),
        None => None,
    };
    let dat = match data {
        Some(s) => Some(cstr(s)?),
        None => None,
    };
    let target_c = cpath(target)?;
    let src_ptr = src.as_ref().map_or(std::ptr::null(), |c| c.as_ptr());
    let typ_ptr = typ.as_ref().map_or(std::ptr::null(), |c| c.as_ptr());
    // The BSD `mount(2)` takes `data` as a mutable pointer (it is a varargs
    // buffer the kernel may read back into on some systems), Linux as a const
    // one. Both are reached from this one expression, produced as `*mut` and
    // cast back down to `*const` on the Linux branch. The pointee is a
    // `CString` that outlives the call either way, and the kernel does not
    // write through it on any platform zinit supports — hence `*const` on the
    // only branch where the compiler will accept it.
    // Produced as `*mut` because the BSD `mount(2)` declares it that way; the
    // pointed-to bytes are never written (see the safety note at the call).
    let dat_ptr: *mut libc::c_void = match &dat {
        Some(c) => c.as_ptr().cast_mut().cast::<libc::c_void>(),
        None => std::ptr::null_mut(),
    };

    // Every branch below produces an `io::Result<()>` directly, rather than a
    // raw `c_int` that is inspected afterwards. That is what lets the
    // unsupported-platform branch exist at all: there is no `c_int` to return
    // from a platform where `mount(2)` was never declared.

    // SAFETY: every pointer is either null (which `mount(2)` accepts as "none"
    // for the source and, on the BSDs, for the type) or a NUL-terminated
    // string held by a `CString` in this frame for the whole call. The
    // pointers are not retained.
    #[cfg(any(target_os = "linux", target_os = "android"))]
    let rc = unsafe {
        libc::mount(
            src_ptr,
            target_c.as_ptr(),
            typ_ptr,
            flags as libc::c_ulong,
            dat_ptr.cast_const(),
        )
    };
    #[cfg(any(target_os = "linux", target_os = "android"))]
    let out = if rc == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    };

    // SAFETY: as above. Four arguments: the BSD `mount(2)` infers the
    // filesystem type from `data`, so `typ_ptr` is not passed and the
    // `fstype` argument this function takes is ignored on these platforms.
    #[cfg(any(
        target_os = "macos",
        target_os = "ios",
        target_os = "tvos",
        target_os = "watchos",
        target_os = "visionos",
        target_os = "freebsd",
        target_os = "openbsd",
        target_os = "dragonfly",
    ))]
    let out = {
        let _ = typ_ptr;
        // SAFETY: as above.
        let rc = unsafe { libc::mount(src_ptr, target_c.as_ptr(), flags as libc::c_int, dat_ptr) };
        if rc == 0 {
            Ok(())
        } else {
            Err(io::Error::last_os_error())
        }
    };

    // SAFETY: as above. NetBSD appends a `size` argument for the extensible
    // attributes buffer, which zinit never uses, so it passes 0.
    #[cfg(target_os = "netbsd")]
    let out = {
        let _ = typ_ptr;
        // SAFETY: as above.
        let rc =
            unsafe { libc::mount(src_ptr, target_c.as_ptr(), flags as libc::c_int, dat_ptr, 0) };
        if rc == 0 {
            Ok(())
        } else {
            Err(io::Error::last_os_error())
        }
    };

    // No `mount(2)` declaration for this target. Reported, not faked: a
    // supervisor that silently skipped the tmpfs stage would then fail later
    // on a missing `/run`, far from the cause.
    #[cfg(not(any(
        target_os = "linux",
        target_os = "android",
        target_os = "macos",
        target_os = "ios",
        target_os = "tvos",
        target_os = "watchos",
        target_os = "visionos",
        target_os = "freebsd",
        target_os = "openbsd",
        target_os = "netbsd",
        target_os = "dragonfly",
    )))]
    let out: io::Result<()> = {
        let _ = (src_ptr, typ_ptr, dat_ptr, target_c);
        Err(io::Error::new(
            io::ErrorKind::Unsupported,
            "mount(2) is not wrapped for this platform",
        ))
    };

    out
}

/// `umount2(2)` on Linux, `unmount(2)` on the BSDs, with the same `u32` flags.
///
/// The two are the same call with different names and different flag types
/// (`MNT_FORCE` on the BSDs, `MNT_DETACH` semantics of its own on Linux). The
/// caller passes a `u32` and this picks the right spelling.
pub fn umount2(target: &Path, flags: u32) -> io::Result<()> {
    let t = cpath(target)?;

    // SAFETY: a NUL-terminated path alive for the call and an int flag.
    #[cfg(any(target_os = "linux", target_os = "android"))]
    let rc = unsafe { libc::umount2(t.as_ptr(), flags as libc::c_int) };

    // SAFETY: as above. `unmount(2)` is the BSD spelling of the same syscall;
    // it returns -1 with errno on failure like every other libc call.
    #[cfg(any(
        target_os = "macos",
        target_os = "ios",
        target_os = "tvos",
        target_os = "watchos",
        target_os = "visionos",
        target_os = "freebsd",
        target_os = "openbsd",
        target_os = "netbsd",
        target_os = "dragonfly",
    ))]
    let rc = unsafe { libc::unmount(t.as_ptr(), flags as libc::c_int) };

    #[cfg(not(any(
        target_os = "linux",
        target_os = "android",
        target_os = "macos",
        target_os = "ios",
        target_os = "tvos",
        target_os = "watchos",
        target_os = "visionos",
        target_os = "freebsd",
        target_os = "openbsd",
        target_os = "netbsd",
        target_os = "dragonfly",
    )))]
    let rc: libc::c_int = {
        let _ = (t, flags);
        -1
    };

    if rc == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `sethostname(2)`.
///
/// The length argument is `c_int` on Apple and the BSDs and `size_t` on
/// Linux and NetBSD, which is why it goes in as `as _`: the cast is resolved
/// against whatever the field's type is on the target being compiled, and
/// there is no `cfg` to get wrong.
pub fn sethostname(name: &str) -> io::Result<()> {
    let bytes = name.as_bytes();
    if bytes.contains(&0) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "hostname contains an interior NUL",
        ));
    }
    // SAFETY: `bytes` is a live slice for the whole call; `sethostname` copies
    // exactly `len` bytes and does not retain the pointer. The length is cast
    // to the parameter type this platform declares.
    if unsafe { libc::sethostname(bytes.as_ptr().cast::<libc::c_char>(), bytes.len() as _) } != 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(())
    }
}

// `TIOCGSID` and `TIOCSCTTY` are ioctl *request numbers*, and they are not
// exported by the `libc` crate on every platform that has them. They are also
// not guessable: each is an `_IO`/`_IOR` encoding whose value depends on the
// group letter, the command number and the argument size. Rather than
// hardcode a table that would silently be wrong somewhere, the ones that are
// missing are declared here from the platform's own headers, and the ones
// that `libc` does export are used directly.
#[cfg(any(target_os = "linux", target_os = "android"))]
#[allow(clippy::unnecessary_cast)] // same-type on 32-bit, load-bearing elsewhere
const TIOCGSID_REQ: u32 = libc::TIOCGSID as u32;
#[cfg(any(target_os = "freebsd", target_os = "dragonfly", target_os = "openbsd",))]
#[allow(clippy::unnecessary_cast)] // same-type on 32-bit, load-bearing elsewhere
const TIOCGSID_REQ: u32 = libc::TIOCGSID as u32;
// `_IOR('t', 124, int)`: IOC_OUT | (sizeof(int) << 16) | ('t' << 8) | 124.
#[cfg(target_os = "netbsd")]
const TIOCGSID_REQ: u32 = 0x4004_747c;
// macOS removed `TIOCGSID` from <sys/ttycom.h>; Darwin's answer is
// `TIOCGPGRP` (which returns the foreground *process group*, not the session),
// so this call cannot be answered on Darwin and says so.
#[cfg(target_vendor = "apple")]
const TIOCGSID_REQ: u32 = 0;

//
// They are stored as `u64` and cast with `as _` at the `ioctl` call, because
// the request parameter's type is not stable across libc targets: it is
// `c_ulong` under glibc and `c_int` under musl. `as _` makes the cast resolve
// against whatever the function being called declares, so there is no
// platform to get wrong.
// The `as u64` is a no-op on glibc (where `TIOCSCTTY` is already `c_ulong =
// u64`) and load-bearing on musl (where it is `c_int = i32`). Clippy only sees
// the target it is compiling for, so the cast is kept and the lint that
// objects to it on one target is silenced with the reason, rather than the
// code being bent to satisfy whichever target happens to be the host.
#[allow(clippy::unnecessary_cast)]
#[cfg(any(
    target_os = "linux",
    target_os = "android",
    target_os = "freebsd",
    target_os = "dragonfly",
))]
const TIOCSCTTY_REQ: u64 = libc::TIOCSCTTY as u64;
// NetBSD and OpenBSD both spell it `_IO('t', 97)` = IOC_VOID | ('t' << 8) | 97.
#[cfg(any(target_os = "netbsd", target_os = "openbsd"))]
const TIOCSCTTY_REQ: u64 = 0x2000_7461;
// Darwin's <sys/ttycom.h> defines `TIOCSCTTY` as `_IO('t', 97)` =
// IOC_VOID | ('t' << 8) | 97.
#[cfg(target_vendor = "apple")]
const TIOCSCTTY_REQ: u64 = 0x2000_7461;

/// `tcgetsid(2)`: the session id owning this terminal.
///
/// A non-blocking readiness read on a console: it returns `EIO` when there is
/// no session attached yet, which is the normal answer for a tty nobody has
/// logged into.
///
/// # Darwin
///
/// Not available. macOS removed `TIOCGSID` and offers only `TIOCGPGRP`,
/// which answers a different question (the foreground process group, not the
/// session). Rather than return the process group and call it a session — a
/// bug that only shows up as a console service that will not stop — this
/// returns `ENOSYS`, and the console code in `zservice` has an explicit
/// branch for it.
#[cfg(target_vendor = "apple")]
pub fn tcgetsid(fd: RawFd) -> io::Result<i32> {
    let _ = fd;
    Err(io::Error::from_raw_os_error(libc::ENOSYS))
}

/// `tcgetsid(2)`: the session id owning this terminal.
///
/// A non-blocking readiness read on a console: it returns `EIO` when there is
/// no session attached yet, which is the normal answer for a tty nobody has
/// logged into.
#[cfg(not(target_vendor = "apple"))]
pub fn tcgetsid(fd: RawFd) -> io::Result<i32> {
    tcgetioctl_int(fd, TIOCGSID_REQ)
}

fn tcgetioctl_int(fd: RawFd, request: u32) -> io::Result<i32> {
    let mut out: libc::c_int = 0;
    // SAFETY: the request writes exactly one `c_int` through the pointer, and
    // `out` is a live, aligned local. The request number is the platform's own
    // `TIOCGSID` constant.
    if unsafe { libc::ioctl(fd, request as _, &raw mut out) } == 0 {
        Ok(out)
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `ioctl(TIOCSCTTY)` — make this terminal the process's controlling terminal.
///
/// Linux's `TIOCSCTTY` takes the steal flag as its argument; the BSDs take
/// none, so the argument is `0` there. The caller must already be a session
/// leader ([`setsid`]); otherwise the call fails with `ENOTTY`, which is the
/// kernel telling the truth about the ordering.
pub fn ioctl_tiocsctty(fd: RawFd, steal: bool) -> io::Result<()> {
    #[cfg(any(target_os = "linux", target_os = "android"))]
    let arg: libc::c_ulong = if steal { 1 } else { 0 };
    #[cfg(not(any(target_os = "linux", target_os = "android")))]
    let arg: libc::c_ulong = 0;
    #[cfg(not(any(target_os = "linux", target_os = "android")))]
    let _ = steal;
    // SAFETY: the argument is a single unsigned long, which is what the
    // BSDs' `TIOCSCTTY` (no argument) and Linux's (steal flag) both expect,
    // and the request number is the platform's own constant.
    if unsafe { libc::ioctl(fd, TIOCSCTTY_REQ as _, arg) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Privileges (probing lives in `capdetect`, mutation lives here)
// ─────────────────────────────────────────────────────────────────────────────

/// The four ids that define who a process currently is.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Ids {
    /// Real user id.
    pub uid: u32,
    /// Effective user id.
    pub euid: u32,
    /// Real group id.
    pub gid: u32,
    /// Effective group id.
    pub egid: u32,
}

/// Read the current real and effective ids.
///
/// Taken as a group so that the drop of privileges can be *verified* against
/// all four at once. Rule 2 in `DESIGN.md` §9: releasing privilege is not
/// believed, it is checked.
pub fn ids() -> Ids {
    // SAFETY: four getters with no arguments and no preconditions; they cannot
    // fail. `geteuid` is a real syscall, not a cached value, which is what
    // makes the post-drop verification meaningful.
    unsafe {
        Ids {
            uid: libc::getuid() as u32,
            euid: libc::geteuid() as u32,
            gid: libc::getgid() as u32,
            egid: libc::getegid() as u32,
        }
    }
}

/// `setresuid(uid, euid, suid)` — set all three user ids atomically.
///
/// Linux only. The atomic three-argument form exists precisely so that a
/// privileged process cannot be caught between two `setuid` calls with a
/// window in which it can regain privilege (`DESIGN.md` §9 rule 1). BSDs have
/// no such call; there, [`setuid_checked`] is the honest fallback.
#[cfg(any(target_os = "linux", target_os = "android"))]
pub fn setresuid(uid: u32, euid: u32, suid: u32) -> io::Result<()> {
    // SAFETY: three ints, no pointers. Failure leaves the ids unchanged.
    if unsafe { libc::setresuid(uid, euid, suid) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `setresgid(gid, egid, sgid)`. Linux only; see [`setresuid`].
#[cfg(any(target_os = "linux", target_os = "android"))]
pub fn setresgid(gid: u32, egid: u32, sgid: u32) -> io::Result<()> {
    // SAFETY: three ints, no pointers.
    if unsafe { libc::setresgid(gid, egid, sgid) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `setgroups(0, NULL)` — drop every supplementary group.
///
/// The first step of the drop, before either uid or gid is touched, because
/// supplementary groups are the easiest privilege to forget and the one that
/// survives a careless `setuid`.
pub fn setgroups_empty() -> io::Result<()> {
    // SAFETY: a null pointer with a count of zero is the documented way to
    // ask for "no groups"; the kernel checks the count and never dereferences.
    if unsafe { libc::setgroups(0, std::ptr::null()) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `setuid(uid)` — the portable fallback, followed by a verification.
///
/// On a platform without `setresuid` this is the *only* option, and on some
/// of them it has the well-known behaviour of also changing the saved id.
/// That is why the result is checked with [`ids`] instead of assumed, and why
/// the failure is a hard error: a service that silently kept root is worse
/// than a service that refused to start.
pub fn setuid_checked(uid: u32) -> io::Result<()> {
    // SAFETY: one int, no pointers.
    if unsafe { libc::setuid(uid) } != 0 {
        return Err(io::Error::last_os_error());
    }
    verify_dropped(uid)
}

/// `setgid(gid)`, with the same verification rationale as [`setuid_checked`].
pub fn setgid_checked(gid: u32) -> io::Result<()> {
    // SAFETY: one int, no pointers.
    if unsafe { libc::setgid(gid) } != 0 {
        return Err(io::Error::last_os_error());
    }
    let now = ids();
    if now.gid != gid || now.egid != gid {
        return Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            format!(
                "setgid({gid}) did not take: gid={} egid={}",
                now.gid, now.egid
            ),
        ));
    }
    Ok(())
}

/// Assert that the real and effective user ids are both `uid`.
///
/// This is the check `DESIGN.md` §9 rule 2 asks for. It is a separate function
/// so that the `setresuid` path can verify too — the kernel can fail to set
/// what it was asked to set under some LSM configurations, and "asked" is not
/// "done".
pub fn verify_dropped(uid: u32) -> io::Result<()> {
    let now = ids();
    if now.uid != uid || now.euid != uid {
        return Err(io::Error::new(
            io::ErrorKind::PermissionDenied,
            format!(
                "uid drop failed: wanted {uid}, uid={} euid={}",
                now.uid, now.euid
            ),
        ));
    }
    Ok(())
}

/// `prctl(PR_SET_NO_NEW_PRIVS, 1)` — forbid gaining privilege via exec.
///
/// Linux only, and the single most valuable line in the whole drop sequence:
/// after it, a setuid binary a service execs cannot raise that service's
/// privilege. Not a substitute for the uid change, but it makes a mistake in
/// the uid change non-exploitable.
#[cfg(any(target_os = "linux", target_os = "android"))]
pub fn set_no_new_privs() -> io::Result<()> {
    // SAFETY: prctl with PR_SET_NO_NEW_PRIVS takes two int-like arguments;
    // the constant and the value are both compile-time.
    if unsafe { libc::prctl(libc::PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

/// `PER_LINUX`, from `linux/personality.h`.
///
/// Not re-exported by the `libc` crate, and hand-written rather than copied
/// from a header at build time: this crate has no build script and no
/// `pkg-config`, and one more `const` is a smaller price than either.
#[cfg(any(target_os = "linux", target_os = "android"))]
const PER_LINUX: libc::c_ulong = 0x0000;

/// `personality(ADDR_NO_RANDOMIZE | PER_LINUX)` — disable ASLR for a service.
///
/// Linux only. Queried rather than set on purpose: this is a probe, and a
/// probe must have no side effects. An invalid persona (`0xffff_ffff`) makes
/// the kernel answer with the current value and change nothing.
#[cfg(any(target_os = "linux", target_os = "android"))]
pub fn query_personality() -> io::Result<u32> {
    // SAFETY: `personality` takes and returns a persona bitmask; the invalid
    // value is documented to be a pure query that changes nothing.
    let rc = unsafe { libc::personality(!0u32 as libc::c_ulong) };
    if rc == -1 {
        // The kernel answers -1/EINVAL for an unknown persona, so `EINVAL`
        // means "the call exists" and anything else is a real failure.
        let e = io::Error::last_os_error();
        if e.raw_os_error() == Some(libc::EINVAL) {
            return Ok(0);
        }
        return Err(e);
    }
    Ok(rc as u32)
}

/// `personality(PER_LINUX | ADDR_NO_RANDOMIZE)`. Linux only.
#[cfg(any(target_os = "linux", target_os = "android"))]
pub fn set_addr_no_randomize() -> io::Result<()> {
    let want = PER_LINUX | libc::ADDR_NO_RANDOMIZE as libc::c_ulong;
    // SAFETY: one ulong; the kernel validates the persona and returns the
    // previous one.
    if unsafe { libc::personality(want) } == -1 {
        return Err(io::Error::last_os_error());
    }
    Ok(())
}

/// `pidfd_open(2)`: an fd that becomes readable when that exact process dies.
///
/// Linux 5.3+. The value of this call is not "an event when a pid exits" —
///
/// that is what `SIGCHLD` already does — but that the fd refers to *one
/// specific process*. A pid can be recycled the instant it dies; a pidfd
/// cannot. An init that learns "child 1234 died" and then looks up 1234 in a
/// table has a race, and the pidfd backend closes it.
///
/// Routed through `syscall(2)` rather than the libc wrapper because glibc only
/// grew the wrapper in 2.36, and zinit has to run on the glibc of whatever
/// distribution booted it.
#[cfg(any(target_os = "linux", target_os = "android"))]
pub fn pidfd_open(pid: i32) -> io::Result<RawFd> {
    // SAFETY: variadic `syscall` with two integer arguments passed as
    // `c_long`, which is what the kernel's `sys_pidfd_open(pid, flags)`
    // prototype expects. The return value is an fd or -1 with errno set.
    // (x32 is excluded from the capabilities probe for the same reason: a
    // variadic pointer/argument width mismatch. This call passes no
    // pointers, so it is safe there too.)
    let rc = unsafe { libc::syscall(libc::SYS_pidfd_open, pid as libc::c_long, 0 as libc::c_long) };
    if rc < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(rc as RawFd)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Internals
// ─────────────────────────────────────────────────────────────────────────────

/// `Path` → `CString`, refusing an interior NUL.
///
/// Every path-taking wrapper funnels through this so that no wrapper can ever
/// hand the kernel a truncated path — the failure mode where
/// `/run/zinit.sock` becomes `/run/zinit` and the init quietly serves the
/// wrong socket.
fn cpath(p: &Path) -> io::Result<CString> {
    CString::new(p.as_os_str().as_bytes()).map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("path contains an interior NUL: {}", p.display()),
        )
    })
}

fn cstr(s: &str) -> io::Result<CString> {
    CString::new(s).map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "interior NUL"))
}

use core::mem::{align_of, size_of};

const fn len_of<T>() -> usize {
    size_of::<T>()
}

/// `sizeof(T)`, kept as a named function so the control-message arithmetic
/// below reads as layout rather than as a pile of `size_of` calls.
const fn hdr_size_of<T>() -> usize {
    size_of::<T>()
}

/// Round a length up to the control buffer's alignment.
///
/// POSIX requires control data to begin at an `size_t`-aligned offset even
/// when the header itself is smaller, and several platforms enforce it.
const fn cmsg_align(len: usize) -> usize {
    (len + align_of::<usize>() - 1) & !(align_of::<usize>() - 1)
}
