type = console
command = /sbin/agetty %i
tty = /dev/%i
depends = net, opt:log
restart = always
restart-budget = 3 restarts per 60s
restart-delay = 250ms
ready = notify
watchdog-sec = 30
user = 99:99
env = A=1
log = file:/var/log/x.log
